### PR TITLE
Feature/update payex logo

### PR DESCRIPTION
**Pull request by WMeander**
Updates made for Payex Logo and Identity page

## Description
New logos added for Payex from UX. Updated Identity page with size examples.

## Motivation and Context
Requirement from UX designer.

## How Has This Been Tested?
- Review from UX designer,
- Added unit tests for payex identity page.
- Checked so Swedbank Pay Identity logotyp page still works. (Differs from published develop version)

## Screenshots (if appropriate):
Old: 
image
New:
image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by eskilsen — COMMENTED** [review]
Looks good! 💯 
Just a thought; Shouldn't the examples be inside the same component preview section?

**Comment by WMeander** [comment]
> Looks good! 💯 Just a thought; Shouldn't the examples be inside the same component preview section?

Hm, maybe. I didn't get any requirements for how they should be presented in the story so i tried to follow the "black/white" logo from SP page.

**Comment by WMeander** [comment]
@eskilsen Updated logo component to include both white & green logo now: 
image

**Comment by eskilsen** [comment]
Nice! 
I think that looks better 😄 

Something is wrong with my notification settings, so I haven't noticed your answer!

**Review by eskilsen — APPROVED** [review]
Nice! 💯

**Pull request merged**
