### PR TITLE
Feature/compression reporter

### PR DESCRIPTION
**Pull request by VikingTristan**
Add a [compressed size action](https://github.com/marketplace/actions/compressed-size-action)  that reports changes in compressed file sizes on our PRs.

~~This branch is branched out of [PR 280](https://github.com/SwedbankPay/design.swedbankpay.com/pull/280) which is why it currently has a couple of diffs unrelated to this PR.~~

~~Setting to draft until the other PR is merged to avoid confusion~~

### CODE REVIEW

**Comment by VikingTristan** [comment]
Currently fails because of
image

**Comment by VikingTristan** [comment]
@asbjornu Do you have any idea why this is acting up?

**Comment by VikingTristan** [comment]
Hmm I guess it's this line  https://github.com/preactjs/compressed-size-action/blob/master/action.js#L94 where it's not discarding local changes when checking out.

**Comment by VikingTristan** [comment]
But why are there changes to begin with...

I'll come back to this

**Comment by VikingTristan** [comment]
Found the issue.
We `chmox -x` the variable shell script. This is regarded as local changes.
By adding `git config core.filemode false` we disregard such changes.
Pushing fix.

**Comment by asbjornu** [comment]
Beautiful! 😍

**Comment by VikingTristan** [comment]
As of right now the action looks for js files in `/dist/*.js`, but we currently have them in `/dist/scripts/...` which is why it's reporting a total size of 0 B

Hopefully this will resolve it https://github.com/preactjs/compressed-size-action/pull/14

**Pull request merged**
