### PR TITLE
Feature/component status badges

### PR DESCRIPTION
**Pull request by pthoang**
## Description
Fixes [DG-576](https://payexjira.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=DG&modal=detail&selectedIssue=DG-576)

## How Has This Been Tested?
Ran all existing tests, added test for StatusBadge component

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/App/docutils/StatusBadge/index.js  2
- src/App/docutils/StatusBadge/index.test.js  1
         

Clones removed
==============
+ src/App/ComponentsDocumentation/components/Badge/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=6378490&bid=20691574)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/App/docutils/StatusBadge/index.js  2
- src/App/docutils/StatusBadge/index.test.js  1
         

Clones removed
==============
+ src/App/ComponentsDocumentation/components/Badge/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=6378490&bid=20691574)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/App/docutils/StatusBadge/index.js  2
- src/App/docutils/StatusBadge/index.test.js  1
         

Clones removed
==============
+ src/App/ComponentsDocumentation/components/Badge/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=6378490&bid=20691574)

**Review by VikingTristan — APPROVED** [review]
A+

**Pull request merged**
