### PR TITLE
Feature/mobile sidebar in topbar

### PR DESCRIPTION
**Pull request by pthoang**
## Description
Fixes [DG-521](https://payexjira.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=DG&modal=detail&selectedIssue=DG-521)

Also fixes issue with duplicate EventListeners and handleScrollbar locking the user in certain cases

## How Has This Been Tested?
Ran all existing tests. Added Snapshot tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/scripts/main/topbar/NavMenu.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/scripts/main/topbar/NavMenu.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/ComponentsDocumentation/components/Tables/index.test.js  1
- src/App/ComponentsDocumentation/components/Charts/index.test.js  1
- src/App/ComponentsDocumentation/components/MediaObject/index.js  1
- src/App/ComponentsDocumentation/components/Alerts/index.test.js  6
- src/App/ComponentsDocumentation/start/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Loaders/index.js  1
- src/App/ComponentsDocumentation/components/Links/index.js  1
- src/App/ComponentsDocumentation/components/Dialog/index.js  1
- src/App/ComponentsDocumentation/components/Sidebar/constants.js  1
- src/App/ComponentsDocumentation/components/Dialog/index.test.js  6
- src/App/ComponentsDocumentation/components/ActionList/index.test.js  8
- src/App/ComponentsDocumentation/components/Charts/Introduction/index.test.js  3
- src/App/ComponentsDocumentation/components/Nav/index.js  3
- src/App/ComponentsDocumentation/components/Alerts/index.js  1
- src/App/ComponentsDocumentation/components/Nav/index.test.js  3
- src/App/ComponentsDocumentation/components/MediaObject/index.test.js  8
- src/App/Documentation/components/Topbar/index.test.js  1
- src/App/ComponentsDocumentation/components/Sidebar/index.test.js  8
- src/App/ComponentsDocumentation/components/Datepickers/index.test.js  4
- src/App/ComponentsDocumentation/components/Forms/index.test.js  9
- src/App/ComponentsDocumentation/components/Lists/index.js  19
- src/App/ComponentsDocumentation/components/Breadcrumb/index.js  1
- src/App/ComponentsDocumentation/components/Pagination/index.js  1
- src/App/ComponentsDocumentation/components/Tabs/index.js  1
- src/App/ComponentsDocumentation/components/ProgressSteps/index.test.js  1
- src/App/ComponentsDocumentation/components/InputGroup/index.test.js  1
- src/App/ComponentsDocumentation/components/Buttons/index.test.js  6
- src/App/ComponentsDocumentation/components/Card/index.test.js  7
- src/App/ComponentsDocumentation/components/Accordion/index.js  2
- src/App/ComponentsDocumentation/components/Sheet/index.test.js  4
- src/App/ComponentsDocumentation/components/Footer/index.test.js  4
- src/App/ComponentsDocumentation/components/Charts/index.js  15
- src/App/ComponentsDocumentation/components/Pagination/index.test.js  1
- src/App/ComponentsDocumentation/components/Tabs/index.test.js  4
- src/App/ComponentsDocumentation/components/Expandable/index.js  1
- src/App/ComponentsDocumentation/components/Toast/index.test.js  8
- src/App/ComponentsDocumentation/components/CodeTags/index.js  1
- src/App/Documentation/components/Topbar/index.js  1
- src/App/ComponentsDocumentation/components/Footer/index.js  1
- src/App/ComponentsDocumentation/components/Forms/index.js  1
- src/App/ComponentsDocumentation/components/Badge/index.test.js  7
- src/App/ComponentsDocumentation/components/Charts/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Status/index.js  1
- src/App/ComponentsDocumentation/components/Panel/index.test.js  8
- src/App/ComponentsDocumentation/components/Accordion/index.test.js  7
- src/App/ComponentsDocumentation/components/Badge/index.js  2
- src/App/ComponentsDocumentation/components/Topbar/index.js  2
- src/App/ComponentsDocumentation/components/ProgressSteps/index.js  4
- src/App/ComponentsDocumentation/components/Slab/index.test.js  1
- src/App/ComponentsDocumentation/components/Lists/index.test.js  1
- src/App/ComponentsDocumentation/components/Expandable/index.test.js  7
- src/App/ComponentsDocumentation/components/Tooltips/index.test.js  7
- src/App/ComponentsDocumentation/components/ActionList/index.js  4
- src/App/ComponentsDocumentation/components/Slab/index.js  9
- src/App/ComponentsDocumentation/components/Card/index.js  1
- src/App/ComponentsDocumentation/components/Loaders/index.test.js  4
- src/App/ComponentsDocumentation/components/Breadcrumb/index.test.js  1
- src/App/ComponentsDocumentation/components/Status/index.test.js  8
- src/App/ComponentsDocumentation/components/Topbar/index.test.js  9
- src/App/ComponentsDocumentation/components/Sidebar/index.js  4
- src/App/ComponentsDocumentation/components/Links/index.test.js  1
- src/App/ComponentsDocumentation/components/Datepickers/index.js  1
- src/App/ComponentsDocumentation/components/Tooltips/index.js  2
- src/App/ComponentsDocumentation/components/CodeTags/index.test.js  7
         

Clones removed
==============
+ src/App/Resources/index.js  -1
+ src/scripts/main/topbar/NavMenu.js  -1
+ src/App/Documentation/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/ComponentsDocumentation/components/ActionList/index.js  4
- src/App/ComponentsDocumentation/components/ActionList/index.test.js  8
- src/App/ComponentsDocumentation/components/Badge/index.test.js  7
- src/App/ComponentsDocumentation/components/Forms/index.js  1
- src/App/ComponentsDocumentation/components/MediaObject/index.test.js  8
- src/App/ComponentsDocumentation/components/Charts/index.js  15
- src/App/ComponentsDocumentation/components/Datepickers/index.test.js  4
- src/App/ComponentsDocumentation/components/Status/index.test.js  8
- src/App/ComponentsDocumentation/components/Links/index.js  1
- src/App/ComponentsDocumentation/components/Topbar/index.js  2
- src/App/ComponentsDocumentation/components/Tabs/index.test.js  4
- src/App/ComponentsDocumentation/components/Alerts/index.js  1
- src/App/ComponentsDocumentation/components/Charts/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Lists/index.test.js  1
- src/App/ComponentsDocumentation/components/Nav/index.js  3
- src/App/ComponentsDocumentation/components/Datepickers/index.js  1
- src/App/ComponentsDocumentation/components/Dialog/index.test.js  6
- src/App/Documentation/components/Topbar/index.test.js  1
- src/App/ComponentsDocumentation/components/Breadcrumb/index.test.js  1
- src/App/ComponentsDocumentation/components/CodeTags/index.test.js  7
- src/App/ComponentsDocumentation/components/Pagination/index.test.js  1
- src/App/ComponentsDocumentation/components/Links/index.test.js  1
- src/App/ComponentsDocumentation/components/Accordion/index.js  2
- src/App/ComponentsDocumentation/components/Nav/index.test.js  3
- src/App/ComponentsDocumentation/components/Footer/index.js  1
- src/App/ComponentsDocumentation/components/Buttons/index.test.js  6
- src/App/ComponentsDocumentation/components/Status/index.js  1
- src/App/ComponentsDocumentation/components/Forms/index.test.js  9
- src/App/ComponentsDocumentation/components/CodeTags/index.js  1
- src/App/ComponentsDocumentation/components/Expandable/index.test.js  7
- src/App/ComponentsDocumentation/components/Charts/Introduction/index.test.js  3
- src/App/ComponentsDocumentation/components/Alerts/index.test.js  6
- src/App/ComponentsDocumentation/start/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Tables/index.test.js  1
- src/App/ComponentsDocumentation/components/Lists/index.js  19
- src/App/ComponentsDocumentation/components/Loaders/index.test.js  4
- src/App/ComponentsDocumentation/components/Sidebar/index.js  4
- src/App/ComponentsDocumentation/components/Charts/index.test.js  1
- src/App/ComponentsDocumentation/components/Slab/index.test.js  1
- src/App/ComponentsDocumentation/components/Sidebar/index.test.js  8
- src/App/ComponentsDocumentation/components/Breadcrumb/index.js  1
- src/App/ComponentsDocumentation/components/Tooltips/index.test.js  7
- src/App/ComponentsDocumentation/components/Tooltips/index.js  2
- src/App/ComponentsDocumentation/components/Badge/index.js  2
- src/App/ComponentsDocumentation/components/Topbar/index.test.js  9
- src/App/ComponentsDocumentation/components/MediaObject/index.js  1
- src/App/ComponentsDocumentation/components/Toast/index.test.js  8
- src/App/ComponentsDocumentation/components/InputGroup/index.test.js  1
- src/App/ComponentsDocumentation/components/Slab/index.js  9
- src/App/ComponentsDocumentation/components/Loaders/index.js  1
- src/App/ComponentsDocumentation/components/Expandable/index.js  1
- src/App/ComponentsDocumentation/components/Footer/index.test.js  4
- src/App/ComponentsDocumentation/components/Tabs/index.js  1
- src/App/ComponentsDocumentation/components/Accordion/index.test.js  7
- src/App/ComponentsDocumentation/components/Card/index.test.js  7
- src/App/ComponentsDocumentation/components/ProgressSteps/index.js  4
- src/App/ComponentsDocumentation/components/Panel/index.test.js  8
- src/App/ComponentsDocumentation/components/Pagination/index.js  1
- src/App/ComponentsDocumentation/components/Dialog/index.js  1
- src/App/ComponentsDocumentation/components/Sheet/index.test.js  4
- src/App/ComponentsDocumentation/components/Sidebar/constants.js  1
- src/App/Documentation/components/Topbar/index.js  1
- src/App/ComponentsDocumentation/components/Card/index.js  1
- src/App/ComponentsDocumentation/components/ProgressSteps/index.test.js  1
         

Clones removed
==============
+ src/App/Documentation/index.js  -1
+ src/App/Resources/index.js  -1
+ src/scripts/main/topbar/NavMenu.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- src/App/ComponentsDocumentation/components/Topbar/index.test.js  8
- src/App/ComponentsDocumentation/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Topbar/index.js  1
- src/App/Core/core/Page-layout/index.js  2
         

Clones removed
==============
+ src/scripts/main/topbar/NavMenu.js  -1
+ src/App/Resources/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- src/App/ComponentsDocumentation/Introduction/index.js  2
- src/App/ComponentsDocumentation/components/Topbar/index.js  1
- src/App/ComponentsDocumentation/components/Topbar/index.test.js  8
- src/App/Core/core/Page-layout/index.js  2
         

Clones removed
==============
+ src/scripts/main/topbar/NavMenu.js  -1
+ src/App/Resources/index.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- src/App/Core/core/Page-layout/index.js  2
- src/App/ComponentsDocumentation/components/Topbar/index.js  1
- src/App/ComponentsDocumentation/components/Topbar/index.test.js  8
- src/App/ComponentsDocumentation/Introduction/index.js  2
         

Clones removed
==============
+ src/App/Resources/index.js  -1
+ src/scripts/main/topbar/NavMenu.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5503610&bid=18038822)

**Comment by pthoang** [comment]
Will open another PR with more changes including these changes

**Pull request closed without merging**
