### PR TITLE
Feature/code view

### PR DESCRIPTION
**Pull request by pthoang**
## Description
Fixes [DG-421](https://payexjira.atlassian.net/secure/RapidBoard.jspa?rapidView=80&projectKey=DG&modal=detail&selectedIssue=DG-421)

## How Has This Been Tested?
Ran all existing tests

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by VikingTristan** [comment]
> Can we please test how this can be implemented in the Developer Portal before we settle on the HTML? From what I can see, the suggested HTML may not be simple to replicate with Markdown as a source.

REF: our little slack meeting :)
https://developer.swedbankpay.com/checkout/payment-menu#step-4-display-the-payment-menu

**Comment by VikingTristan** [comment]
The final looks of it looks great! 👍

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/Documentation/components/CodeView/index.js  2
- src/App/Documentation/utils/ComponentPreview/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5368021&bid=17592178)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/Documentation/utils/ComponentPreview/index.js  2
- src/App/Documentation/components/CodeView/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5368021&bid=17592178)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/Documentation/utils/ComponentPreview/index.js  2
- src/App/Documentation/components/CodeView/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5368021&bid=17592178)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/App/Documentation/utils/ComponentPreview/index.js  2
- src/App/Documentation/components/CodeView/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/design.swedbankpay.com/pullRequest?prid=5368021&bid=17592178)

**Pull request merged**
